"""Adicionando telefone para o profissional

Revision ID: 73730faaa6bf
Revises: d0f028634731
Create Date: 2025-06-23 22:29:31.924959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73730faaa6bf'
down_revision = 'd0f028634731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
