"""Criação inicial do banco

Revision ID: fb388a6af780
Revises: 
Create Date: 2025-06-22 22:02:15.716645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb388a6af780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('idAdministrador', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('idAdministrador'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('idCliente')
    )
    op.create_table('profissionais',
    sa.Column('idProfissional', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('idProfissional'),
    sa.UniqueConstraint('email')
    )
    op.create_table('servicos',
    sa.Column('idServico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idServico')
    )
    op.create_table('agendas',
    sa.Column('idAgenda', sa.Integer(), nullable=False),
    sa.Column('idProfissional', sa.Integer(), nullable=False),
    sa.Column('diaSemana', sa.Integer(), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFim', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['idProfissional'], ['profissionais.idProfissional'], ),
    sa.PrimaryKeyConstraint('idAgenda')
    )
    op.create_table('profissional_servicos',
    sa.Column('idProfissionalServico', sa.Integer(), nullable=False),
    sa.Column('idProfissional', sa.Integer(), nullable=False),
    sa.Column('idServico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProfissional'], ['profissionais.idProfissional'], ),
    sa.ForeignKeyConstraint(['idServico'], ['servicos.idServico'], ),
    sa.PrimaryKeyConstraint('idProfissionalServico')
    )
    op.create_table('agendamentos',
    sa.Column('idAgendamento', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idProfissionalServico', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horaInicio', sa.Time(), nullable=False),
    sa.Column('horaFim', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['idCliente'], ['clientes.idCliente'], ),
    sa.ForeignKeyConstraint(['idProfissionalServico'], ['profissional_servicos.idProfissionalServico'], ),
    sa.PrimaryKeyConstraint('idAgendamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('profissional_servicos')
    op.drop_table('agendas')
    op.drop_table('servicos')
    op.drop_table('profissionais')
    op.drop_table('clientes')
    op.drop_table('administradores')
    # ### end Alembic commands ###
